global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend_active:4000']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
